"""HTML reporter: write function info, crashes, and coverage as standalone HTML pages."""

from __future__ import annotations

from pathlib import Path

from futagassist.core.schema import CrashInfo, CoverageReport, FunctionInfo

_CSS = """
<style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
           margin: 2rem auto; max-width: 960px; color: #1a1a2e; background: #f8f9fa; }
    h1, h2 { color: #16213e; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    th, td { border: 1px solid #dee2e6; padding: 0.5rem 0.75rem; text-align: left; }
    th { background: #e9ecef; font-weight: 600; }
    tr:nth-child(even) { background: #f1f3f5; }
    .badge { display: inline-block; padding: 0.2em 0.5em; border-radius: 4px;
             font-size: 0.85em; font-weight: 600; }
    .badge-api { background: #d4edda; color: #155724; }
    .badge-fuzz { background: #cce5ff; color: #004085; }
    .badge-crash { background: #f8d7da; color: #721c24; }
    .progress-bar { background: #e9ecef; border-radius: 4px; overflow: hidden; height: 1.5rem; }
    .progress-fill { background: #28a745; height: 100%; display: flex;
                     align-items: center; padding: 0 0.5rem; color: #fff; font-size: 0.85rem; }
    footer { margin-top: 2rem; color: #6c757d; font-size: 0.85rem; }
</style>
"""


def _html_page(title: str, body: str) -> str:
    """Wrap body in a minimal HTML page."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{title} — FutagAssist</title>
    {_CSS}
</head>
<body>
    <h1>{title}</h1>
    {body}
    <footer>Generated by FutagAssist</footer>
</body>
</html>
"""


def _esc(s: str) -> str:
    """Escape HTML special characters."""
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


class HtmlReporter:
    """Reporter that writes standalone HTML pages for functions, crashes, and coverage."""

    format_name: str = "html"

    def report_functions(self, functions: list[FunctionInfo], output: Path) -> None:
        """Write function info as an HTML table."""
        output = Path(output).resolve()
        output.parent.mkdir(parents=True, exist_ok=True)

        rows = []
        for fn in functions:
            badges = ""
            if fn.is_api:
                badges += '<span class="badge badge-api">API</span> '
            if fn.is_fuzz_target_candidate:
                badges += '<span class="badge badge-fuzz">Fuzz</span> '
            rows.append(
                f"<tr><td>{_esc(fn.name)}</td>"
                f"<td><code>{_esc(fn.signature)}</code></td>"
                f"<td>{_esc(fn.file_path)}:{fn.line}</td>"
                f"<td>{badges.strip()}</td></tr>"
            )

        body = f"""
        <p>{len(functions)} function(s) extracted.</p>
        <table>
            <thead><tr><th>Name</th><th>Signature</th><th>Location</th><th>Tags</th></tr></thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """
        output.write_text(_html_page("Functions Report", body), encoding="utf-8")

    def report_crashes(self, crashes: list[CrashInfo], output: Path) -> None:
        """Write crash info as an HTML table."""
        output = Path(output).resolve()
        output.parent.mkdir(parents=True, exist_ok=True)

        rows = []
        for c in crashes:
            rows.append(
                f'<tr><td><span class="badge badge-crash">{_esc(c.warn_class or "CRASH")}</span></td>'
                f"<td>{_esc(c.summary)}</td>"
                f"<td>{_esc(c.crash_file)}:{c.crash_line}</td>"
                f"<td>{_esc(c.artifact_path)}</td></tr>"
            )

        body = f"""
        <p>{len(crashes)} crash(es) found.</p>
        <table>
            <thead><tr><th>Type</th><th>Summary</th><th>Location</th><th>Artifact</th></tr></thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """
        output.write_text(_html_page("Crash Report", body), encoding="utf-8")

    def report_coverage(self, data: CoverageReport, output: Path) -> None:
        """Write coverage summary as an HTML page with progress bar."""
        output = Path(output).resolve()
        output.parent.mkdir(parents=True, exist_ok=True)

        line_pct = (data.lines_covered / data.lines_total * 100) if data.lines_total else 0
        region_pct = (data.regions_covered / data.regions_total * 100) if data.regions_total else 0

        body = f"""
        <h2>Line Coverage</h2>
        <div class="progress-bar">
            <div class="progress-fill" style="width:{line_pct:.1f}%">{data.lines_covered}/{data.lines_total} ({line_pct:.1f}%)</div>
        </div>

        <h2>Region Coverage</h2>
        <div class="progress-bar">
            <div class="progress-fill" style="width:{region_pct:.1f}%">{data.regions_covered}/{data.regions_total} ({region_pct:.1f}%)</div>
        </div>

        <table>
            <thead><tr><th>Metric</th><th>Covered</th><th>Total</th><th>%</th></tr></thead>
            <tbody>
                <tr><td>Lines</td><td>{data.lines_covered}</td><td>{data.lines_total}</td><td>{line_pct:.1f}%</td></tr>
                <tr><td>Regions</td><td>{data.regions_covered}</td><td>{data.regions_total}</td><td>{region_pct:.1f}%</td></tr>
            </tbody>
        </table>
        <p><strong>Binary:</strong> <code>{_esc(data.binary_path)}</code></p>
        """
        output.write_text(_html_page("Coverage Report", body), encoding="utf-8")
